### ISSUE TITLE
error after terraform configuration

### ISSUE THREAD

**Issue by Luubosi** [suzuki-shunsuke/go-graylog#127]
hi, please advice.
I have these errors after application terraform configuration and restart graylog docker container. With manual configuration after restart graylog is ok.
Please, did you test terraform code to docker imlementation?  After restart is it working?
phanks

```
2019-07-03 15:15:34,840 INFO : org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2019-07-03 15:15:35,094 INFO : org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2019-07-03 15:15:36,191 INFO : org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2019-07-03 15:15:36,246 INFO : org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2019-07-03 15:15:36,297 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:75}] to mongo:27017
2019-07-03 15:15:36,316 INFO : org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2019-07-03 15:15:36,367 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2019-07-03 15:15:36,390 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): Error injecting constructor, java.lang.NullPointerException
2019-07-03 15:15:36,390 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): Error injecting constructor, java.lang.NullPointerException
2019-07-03 15:15:36,391 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): Error injecting constructor, java.lang.NullPointerException
2019-07-03 15:15:36,391 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): Error injecting constructor, java.lang.NullPointerException
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at org.graylog2.shared.buffers.ProcessBuffer.<init>(ProcessBuffer.java:59)
  at org.graylog2.shared.bindings.GenericBindings.configure(GenericBindings.java:60)
  while locating org.graylog2.shared.buffers.ProcessBuffer
    for the 2nd parameter of org.graylog2.periodical.ThrottleStateUpdaterThread.<init>(ThrottleStateUpdaterThread.java:76)
  while locating org.graylog2.periodical.ThrottleStateUpdaterThread
  while locating org.graylog2.plugin.periodical.Periodical annotated with @com.google.inject.internal.Element(setName=,uniqueId=354, type=MULTIBINDER, keyType=)
  while locating java.util.Set<org.graylog2.plugin.periodical.Periodical>
    for the 3rd parameter of org.graylog2.shared.initializers.PeriodicalsService.<init>(PeriodicalsService.java:45)
  at org.graylog2.shared.initializers.PeriodicalsService.class(PeriodicalsService.java:36)
  while locating org.graylog2.shared.initializers.PeriodicalsService
  while locating com.google.common.util.concurrent.Service annotated with @com.google.inject.internal.Element(setName=,uniqueId=7, type=MULTIBINDER, keyType=)
  while locating java.util.Set<com.google.common.util.concurrent.Service>
    for field at org.graylog2.shared.bindings.providers.ServiceManagerProvider.services(ServiceManagerProvider.java:34)
  while locating org.graylog2.shared.bindings.providers.ServiceManagerProvider
  at org.graylog2.shared.bindings.GenericBindings.configure(GenericBindings.java:64)
  while locating com.google.common.util.concurrent.ServiceManager
Caused by: java.lang.NullPointerException
        at org.graylog2.streams.StreamRuleMatcherFactory.build(StreamRuleMatcherFactory.java:31)
        at org.graylog2.streams.StreamRouterEngine$Rule.<init>(StreamRouterEngine.java:278)
        at org.graylog2.streams.StreamRouterEngine.<init>(StreamRouterEngine.java:98)
        at org.graylog2.streams.StreamRouterEngine$$FastClassByGuice$$c6190f39.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
        at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:836)
        at com.sun.proxy.$Proxy41.create(Unknown Source)
        at org.graylog2.streams.StreamRouter$StreamRouterEngineUpdater.getNewEngine(StreamRouter.java:136)
        at org.graylog2.streams.StreamRouter$StreamRouterEngineUpdater.access$000(StreamRouter.java:102)
        at org.graylog2.streams.StreamRouter.<init>(StreamRouter.java:62)
        at org.graylog2.streams.StreamRouter$$FastClassByGuice$$f9455617.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:198)
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:151)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.i
```ntern

**Comment by suzuki-shunsuke** [comment]
Hello.
Please tell us how to reproduce.

* terraform version
* terraform-provider-graylog version
* Graylog version
* How to setup Graylog. For example, if you use Docker Compose, please share docker-compose.yml

And it is the Graylog's problem.
Unfortunately, I think the Graylog API's validation isn't adequate and we can break Graylog with Graylog API.
You should contact the Graylog community (ex. https://community.graylog.org ).

**Comment by suzuki-shunsuke** [comment]
terraform simply call Graylog API.
If Graylog break when we call the Graylog API, it is not client problem but Graylog's problem.

**Comment by Luubosi** [comment]
for reproduce:
Terraform v0.12.2
terraform-provider-graylog_v3.3.0_windows_amd64
graylog/graylog:3.0.2

```
version: '2'
networks:
  default:
    external:
      name: dockergraylog_default
services:
# MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    container_name: mongodb
    restart: always
    volumes:
      - /opt/mongodb:/data/db
    ports:
      - 27017:27017

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    volumes:
      - /opt/elasticsearch_graylog/data:/usr/share/elasticsearch/data

  # Graylog: https://hub.docker.com/r/graylog/graylo
  # https://docs.graylog.org/en/3.0/pages/installation/docker.html
  graylog:
    image: graylog/graylog:3.0.2
    container_name: graylog
    restart: always
    volumes:
      - /opt/graylog_etc/journal:/usr/share/graylog/data/journal
      - /opt/graylog_etc/server:/etc/graylog/server
      - /opt/graylog_etc/plugin:/usr/share/graylog/plugin
    environment:
      - GRAYLOG_IS_MASTER=true
      - GRAYLOG_ROOT_TIMEZONE=Europe/Bratislava
      - GRAYLOG_ELASTICSEARCH_SHARDS=1
      - GRAYLOG_ELASTICSEARCH_REPLICAS=0
      - GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE=3gb
      - GRAYLOG_SERVER_JAVA_OPTS=-Xms3g -Xmx3g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
      - GRAYLOG_PASSWORD_SECRET=secretsecretsecretsecretsecret
      # Password: echo -n PASSWORD | shasum -a 256
      - GRAYLOG_ROOT_PASSWORD_SHA2=Password-output
      - GRAYLOG_HTTP_PUBLISH_URI=http://fqdn:9000/
      - GRAYLOG_HTTP_EXTERNAL_URI=http://fqdn:9000/

    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      #- 443:443
      # INPUT_TDAGENT
      - 20800:20800
      # INPUT_SYSLOG_TCP
      - 20517:20517

```

terraform code, there is complete configuration, i will investigate if some source is problem.
for example, to create input - gelf tcp/udp, syslog tcp/udp.
